// <auto-generated />
using System;
using HospitalAccess.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HospitalAccess.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AccessDbContext))]
    [Migration("20260729171727_AddWelcomeFontPath")]
    partial class AddWelcomeFontPath
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("user_code_seq");

            modelBuilder.Entity("HospitalAccess.Domain.Entities.AccessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ControllerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ControllerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ControllerSerialNumber")
                        .HasColumnType("text");

                    b.Property<int?>("Direction")
                        .HasColumnType("integer");

                    b.Property<bool>("Granted")
                        .HasColumnType("boolean");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<int>("RawEventCode")
                        .HasColumnType("integer");

                    b.Property<long?>("RecordSerialNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UserCode")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("ControllerSerialNumber", "RecordSerialNumber")
                        .IsUnique()
                        .HasFilter("\"RecordSerialNumber\" IS NOT NULL AND \"ControllerSerialNumber\" IS NOT NULL");

                    b.ToTable("AccessLogs");
                });

            modelBuilder.Entity("HospitalAccess.Domain.Entities.AccessPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ControllerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GrantedByGroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("TimeGroup")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ControllerId");

                    b.HasIndex("UserId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("HospitalAccess.Domain.Entities.AlarmEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Cleared")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ControllerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ControllerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int>("RawEventCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("AlarmEvents");
                });

            modelBuilder.Entity("HospitalAccess.Domain.Entities.BedStay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ControllerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByUsername")
                        .HasColumnType("text");

                    b.Property<int?>("EndReason")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndedByUsername")
                        .HasColumnType("text");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VisitorUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ControllerId")
                        .IsUnique()
                        .HasFilter("\"EndedAtUtc\" IS NULL");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("VisitorUserId");

                    b.ToTable("BedStays");
                });

            modelBuilder.Entity("HospitalAccess.Domain.Entities.Controller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiBaseUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApiPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApiToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ApiTokenUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApiUsername")
                        .HasColumnType("text");

                    b.Property<string>("CommunicationPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConnectionMode")
                        .HasColumnType("integer");

                    b.Property<string>("HomeAssistantRoomId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRoom")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastClockSyncAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastReachError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSeenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<int>("RestartCount")
                        .HasColumnType("integer");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SupportsWaitRepeatMessage")
                        .HasColumnType("boolean");

                    b.Property<int>("TimeoutMs")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Controllers");
                });

            modelBuilder.Entity("HospitalAccess.Domain.Entities.ControllerAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ControllerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ControllerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("PerformedByUsername")
                        .HasColumnType("text");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ControllerId");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("ControllerAuditLogs");
                });

            modelBuilder.Entity("HospitalAccess.Domain.Entities.DeviceSyncStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("ConflictUserCode")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ControllerId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ControllerId");

                    b.HasIndex("UserId", "ControllerId")
                        .IsUnique();

                    b.ToTable("SyncStatuses");
                });

            modelBuilder.Entity("HospitalAccess.Domain.Entities.EventPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ControllerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ControllerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DownloadedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("ImageJpg")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("RawEventCode")
                        .HasColumnType("integer");

                    b.Property<long?>("UserCode")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("EventPhotos");
                });

            modelBuilder.Entity("HospitalAccess.Domain.Entities.GroupControllerDefault", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ControllerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ControllerId");

                    b.HasIndex("GroupId", "ControllerId")
                        .IsUnique();

                    b.ToTable("GroupControllerDefaults");
                });

            modelBuilder.Entity("HospitalAccess.Domain.Entities.Holiday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("HolidayType")
                        .HasColumnType("smallint");

                    b.Property<byte>("Index")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RepeatsYearly")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Index")
                        .IsUnique();

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("HospitalAccess.Domain.Entities.StaffUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("StaffUsers");
                });

            modelBuilder.Entity("HospitalAccess.Domain.Entities.SystemSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessLogRetentionDays")
                        .HasColumnType("integer");

                    b.Property<int>("AlarmLogRetentionDays")
                        .HasColumnType("integer");

                    b.Property<int>("ControllerAuditRetentionDays")
                        .HasColumnType("integer");

                    b.Property<bool>("DevelopmentModeEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("DeviceDefaultApiPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceDefaultCommunicationPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EventPhotoRetentionDays")
                        .HasColumnType("integer");

                    b.Property<string>("HomeAssistantBaseUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeAssistantClearService")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("HomeAssistantEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("HomeAssistantToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeAssistantWelcomeService")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QrFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUsername")
                        .HasColumnType("text");

                    b.Property<string>("WelcomeBaseImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WelcomeFontColorHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WelcomeFontPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float?>("WelcomeFontSize")
                        .HasColumnType("real");

                    b.Property<string>("WelcomePublicBaseUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("WelcomeTextY")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000aa"),
                            AccessLogRetentionDays = 0,
                            AlarmLogRetentionDays = 0,
                            ControllerAuditRetentionDays = 0,
                            DevelopmentModeEnabled = false,
                            DeviceDefaultApiPassword = "",
                            DeviceDefaultCommunicationPassword = "",
                            EventPhotoRetentionDays = 90,
                            HomeAssistantBaseUrl = "",
                            HomeAssistantClearService = "",
                            HomeAssistantToken = "",
                            HomeAssistantWelcomeService = "",
                            QrFormat = "PlainText",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WelcomeBaseImagePath = "",
                            WelcomeFontColorHex = "",
                            WelcomeFontPath = "",
                            WelcomePublicBaseUrl = ""
                        });
                });

            modelBuilder.Entity("HospitalAccess.Domain.Entities.TimeGroupSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("GroupNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupNumber")
                        .IsUnique();

                    b.ToTable("TimeGroupSchedules");
                });

            modelBuilder.Entity("HospitalAccess.Domain.Entities.TimeGroupSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("BeginTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<byte>("SegmentIndex")
                        .HasColumnType("smallint");

                    b.Property<Guid>("TimeGroupScheduleId")
                        .HasColumnType("uuid");

                    b.Property<byte>("Weekday")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("TimeGroupScheduleId", "Weekday", "SegmentIndex")
                        .IsUnique();

                    b.ToTable("TimeGroupSegments");
                });

            modelBuilder.Entity("HospitalAccess.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("CardNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUsername")
                        .HasColumnType("text");

                    b.Property<string>("Document")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("text");

                    b.Property<byte[]>("FacePhoto")
                        .HasColumnType("bytea");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByUsername")
                        .HasColumnType("text");

                    b.Property<int>("TimeGroup")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<long>("UserCode")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserCode")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HospitalAccess.Domain.Entities.UserAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("PerformedByUsername")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserCode")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("UserId");

                    b.ToTable("UserAuditLogs");
                });

            modelBuilder.Entity("HospitalAccess.Domain.Entities.UserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("HospitalAccess.Domain.Entities.AccessPermission", b =>
                {
                    b.HasOne("HospitalAccess.Domain.Entities.Controller", "Controller")
                        .WithMany("Permissions")
                        .HasForeignKey("ControllerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalAccess.Domain.Entities.User", "User")
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Controller");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HospitalAccess.Domain.Entities.BedStay", b =>
                {
                    b.HasOne("HospitalAccess.Domain.Entities.Controller", "Controller")
                        .WithMany()
                        .HasForeignKey("ControllerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalAccess.Domain.Entities.User", "VisitorUser")
                        .WithMany()
                        .HasForeignKey("VisitorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Controller");

                    b.Navigation("VisitorUser");
                });

            modelBuilder.Entity("HospitalAccess.Domain.Entities.DeviceSyncStatus", b =>
                {
                    b.HasOne("HospitalAccess.Domain.Entities.Controller", "Controller")
                        .WithMany()
                        .HasForeignKey("ControllerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalAccess.Domain.Entities.User", "User")
                        .WithMany("SyncStatuses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Controller");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HospitalAccess.Domain.Entities.GroupControllerDefault", b =>
                {
                    b.HasOne("HospitalAccess.Domain.Entities.Controller", "Controller")
                        .WithMany()
                        .HasForeignKey("ControllerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalAccess.Domain.Entities.UserGroup", "Group")
                        .WithMany("DefaultControllers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Controller");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("HospitalAccess.Domain.Entities.TimeGroupSegment", b =>
                {
                    b.HasOne("HospitalAccess.Domain.Entities.TimeGroupSchedule", "Schedule")
                        .WithMany("Segments")
                        .HasForeignKey("TimeGroupScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("HospitalAccess.Domain.Entities.User", b =>
                {
                    b.HasOne("HospitalAccess.Domain.Entities.UserGroup", "Group")
                        .WithMany("Users")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("HospitalAccess.Domain.Entities.Controller", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("HospitalAccess.Domain.Entities.TimeGroupSchedule", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("HospitalAccess.Domain.Entities.User", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("SyncStatuses");
                });

            modelBuilder.Entity("HospitalAccess.Domain.Entities.UserGroup", b =>
                {
                    b.Navigation("DefaultControllers");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
